export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SET_USER_TYPE = "SET_USER_TYPE";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const PATIENT_SIGNUP_SUCCESS = "PATIENT_SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";



